export const questions = [
  {
    id: 0,
    text: 'Does your child experience asthma symptoms more than 2 nights per week? (Such as persistent cough, night-time awakenings, need for inhaler use)',
    yesContent: 'Info for if they say yes',
    noContent: 'Info for if they say no',
    expandedRecommendationsIndicator: 'Yes',
  },
  {
    id: 1,
    text: 'Does your child get asthma symptoms in the mornings such as coughing, breathing problems (shortness of breath, rapid breathing, or gasping for air), or wheezing, (which causes a whistling sound when they breathe out)?',
    yesContent: 'Info for if they say yes',
    noContent: 'Info for if they say no',
    expandedRecommendationsIndicator: 'Yes',
  },
  {
    id: 2,
    text: 'Is your child limited in activities such as running, exercise, or school sports?',
    yesContent: 'Info for if they say yes',
    noContent: 'Info for if they say no',
    expandedRecommendationsIndicator: 'Yes',
  },
  {
    id: 3,
    text: 'Does anyone in your family smoke?',
    yesContent: 'Info for if they say yes',
    noContent: 'Info for if they say no',
    expandedRecommendationsIndicator: 'Yes',
  },
  {
    id: 4,
    text: "Does your child's pillow or mattress have a zipper cover for allergies?",
    yesContent: 'Info for if they say yes',
    noContent: 'Info for if they say no',
    expandedRecommendationsIndicator: 'No',
  },
  {
    id: 5,
    text: "Does your child's room have carpet or rugs?",
    yesContent: 'Info for if they say yes',
    noContent: 'Info for if they say no',
    expandedRecommendationsIndicator: 'Yes',
  },
  {
    id: 6,
    text: 'Does your child have constant exposure to water damaged surface, visible mold, or mildew?',
    yesContent: 'Info for if they say yes',
    noContent: 'Info for if they say no',
    expandedRecommendationsIndicator: 'Yes',
  },
  {
    id: 7,
    text: 'Does your family have any furry pets (dogs, cats, rabbits, etc)?',
    yesContent: 'Info for if they say yes',
    noContent: 'Info for if they say no',
    expandedRecommendationsIndicator: 'Yes',
  },
  {
    id: 8,
    text: "Have you ever run out of your child's medications?",
    yesContent: 'Info for if they say yes',
    noContent: 'Info for if they say no',
    expandedRecommendationsIndicator: 'Yes',
  },
  {
    id: 9,
    text: 'Does your child have a spacer for their inhaler and know how to use it?',
    yesContent: 'Info for if they say yes',
    noContent: 'Info for if they say no',
    expandedRecommendationsIndicator: 'No',
  },
  {
    id: 10,
    text: 'Does your child have an asthma action plan during asthma attacks?',
    yesContent: 'Info for if they say yes',
    noContent: 'Info for if they say no',
    expandedRecommendationsIndicator: 'No',
  },
  {
    id: 11,
    text: 'Does your child take their asthma medication more than recommended?',
    yesContent: 'Info for if they say yes',
    noContent: 'Info for if they say no',
    expandedRecommendationsIndicator: 'Yes',
  },
];
